FROM python:3

ENV HOME /tmp
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /opt/app
COPY ./requirements.txt /opt/app/requirements.txt

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

ENTRYPOINT ["/opt/app/entrypoint.develop.sh"]

